### PR TITLE
parseFacultyInfo.py and readme.md updated.

### PR DESCRIPTION
**Pull request by rahulkapoor90**
Added indent=4 in order to beautify json file and moved faculty_info.json file so that it is created and result is appended even if the connection terminates.

### CODE REVIEW

**Comment by rahulkapoor90** [comment]
@kishore-narendran Will this pull request be open forever?

**Comment by kishore-narendran** [comment]
I'm sorry I hadn't noticed it until now.

**Comment by rahulkapoor90** [comment]
thanks @kishore-narendran

**Comment by aneesh-neelam** [comment]
Why was requirements.txt deleted? 

You install the dependencies via `pip install -r requirements.txt`. 
Now you have to install all of them manually. Putting those in README.md is moot.

**Comment by rahulkapoor90** [comment]
sorry, that was my bad. since i use pycharm i thought requirements was not needed but i'll send a new pull request with the file soon.

**Comment by kishore-narendran** [comment]
I added it, don't worry about it!

**Pull request merged**
